services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StrongPassword@123' -C -Q \"SELECT 1\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: keep-improving-api
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=KIdb;
        User Id=sa;
        Password=StrongPassword@123;
        TrustServerCertificate=True

volumes:
  sqlserver_data: